### PR TITLE
Fix internal errors propagating to stderr

### PR DESCRIPTION
**Pull request by AlexandrosAlexiou**
- Log analyze errors instead of throwing exceptions that propagate to stderr and trigger Neovim pop-up messages when using noice.nvim plugin.
 - Implement general code improvements (visibility modifiers, add explicit types, use val instead of var, default function params)
 - Fix tests
 - Remove unused imports

### CODE REVIEW

**Comment by owl-from-hogvarts** [comment]
LGTM. Except, instead of propagating error we are propagating null value now. What is the end result of the null propagation? I see that it results in `null`s being displayed in user interface at least somewhere

**Comment by owl-from-hogvarts** [comment]
@AlexandrosAlexiou Notifying you, that our organisation has changed name as of your suggestion. Please, update remote repo url in your local clone

**Comment by AlexandrosAlexiou** [comment]
> LGTM. Except, instead of propagating error we are propagating null value now. What is the end result of the null propagation? I see that it results in `null`s being displayed in user interface at least somewhere

Which user interface are you referring to?

**Comment by owl-from-hogvarts** [comment]
Speaking of GUI, I referred to [`Hower.kt:30`](https://github.com/kotlin-community-tools/kotlin-language-server/blob/main/server/src/main/kotlin/org/javacs/kt/hover/Hovers.kt#L30). But, after more thoroughly reviewing code I can confirm, that null won't get into UI.

> [!NOTE]
> Under UI/GUI I mean strings which are being sent to LSP-client to be displayed in the Clinet's UI at the end.

**Comment by owl-from-hogvarts** [comment]
Nope, `null` gets its way to UI in [`Hover.kt:42`](https://github.com/kotlin-community-tools/kotlin-language-server/blob/main/server/src/main/kotlin/org/javacs/kt/hover/Hovers.kt).

Instead of returning null, null is being interpolated into a string. I will implement the check for null there and merge your PR.

**Comment by owl-from-hogvarts** [comment]
Thanks for contribution!

**Comment by AlexandrosAlexiou** [comment]
> Nope, `null` gets its way to UI at [`Hover.kt:42`](https://github.com/kotlin-community-tools/kotlin-language-server/blob/main/server/src/main/kotlin/org/javacs/kt/hover/Hovers.kt).
> 
> Instead of returning null, null is being interpolated into a string. I will implement the check for null there and merge your PR.

Thanks!

**Pull request merged**
