### PR TITLE
Bump Kotlin compiler to 2.0.20

### PR DESCRIPTION
**Pull request by AlexandrosAlexiou**
- Upgrade Gradle wrapper to `8.10.1`
- Add `Guava` to the `platform` module: Started encountering a `NoSuchMethodError` for `systemNanoTime()` after the Kotlin compiler bump, which means that our code is trying to call a method that is not available at runtime. The most likely cause of this issue is a version mismatch between the Guava library in the project and the version that is actually available at runtime.
- Use `PsiTypes` instead of the deprecated and marked to be removed [PsiType](https://github.com/JetBrains/intellij-community/blob/09bdd80767cf25a55597aaa47a31e761d75b8a21/java/java-psi-api/src/com/intellij/psi/PsiType.java#L24)
- Group Gradle tasks, and organize dependencies
- General code improvements

### CODE REVIEW

**Comment by AlexandrosAlexiou** [comment]
By the way, I assume that [fwcd/kotlin-language-server](https://github.com/fwcd/kotlin-language-server) is dead, so I will continue opening PRs here.

**Comment by AlexandrosAlexiou** [comment]
Hello, since this PR has been stale for a while.

Is this fork going to be actively maintained? If not I will resume opening PRs to the original repo.

Thanks

**Comment by Zerumi** [comment]
> Hello, since this PR has been stale for a while.
> 
> Is this fork going to be actively maintained? If not I will resume opening PRs to the original repo.
> 
> Thanks

Hi! We are apologize, because we have some university issues rn, but we will continue developing as soon as we can (in about weeks). Now you may also open PR in original repo, we will pull changes from there

**Comment by AlexandrosAlexiou** [comment]
> > Hello, since this PR has been stale for a while.
> > Is this fork going to be actively maintained? If not I will resume opening PRs to the original repo.
> > Thanks
> 
> Hi! We are thank you for your interest in this project and apologize, because we have some university issues rn, but we will continue developing as soon as we can (in about weeks). Now you may also open PR in original repo, we will pull changes from there

Hi there! Thanks for the update and for keeping me in the loop. I totally understand that university commitments can be quite time-consuming—no need to apologize! I'll go ahead and open any needed PRs on the original repo for now, and I’ll keep an eye out for any updates here once you're able to jump back in. Best of luck with your studies, and looking forward to contributing whenever things are back in full swing! 😊

**Comment by owl-from-hogvarts** [comment]
Thanks for contribution! We indeed don't have much of spare time. We will try to keep project afloat as much as we can.

**Pull request merged**
